### ISSUE TITLE
部分机型显示有问题

### ISSUE THREAD

**Issue by JakeWoki** [AndroidMsky/linkScrollMsky#1]
小米没有问题
Device: Honor SCL-AL00
OS: EMUI3.1.1(Android 5.1.1)
![20170208095246](https://cloud.githubusercontent.com/assets/6948411/22720337/29097128-ede5-11e6-971b-edf902cca218.png)

**Comment by AndroidMsky** [comment]
仅仅是显示层次有问题是，还是滑动也存在问题？

**Comment by JakeWoki** [comment]
滑动也有问题，没有渐变效果

**Comment by AndroidMsky** [comment]
你可以尝试修改一下遮罩层布局，和 app:layout_behavior="com.example.liangmutian.linkscrollmsky.RelativelayoutBehavior">对应控件试一下，我这里没有这款手机不能复现bug

**Comment by JakeWoki** [comment]
最近没时间看，今天再运行了下，又没有问题了  汗
